version: "2"

services:
  web:
    build: .
    command: "yarn run watch"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    ports:
      - "9778:9778"

volumes:
  node_modules:
